Traceback (most recent call last):
  File "C:\Users\mlee\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\mlee\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mlee\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mlee\anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\mlee\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\mlee\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\mlee\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Title_Simple 원-핫 인코딩
title_dummies_train = pd.get_dummies(train['Title_Simple'], prefix='Title')
train = pd.concat([train, title_dummies_train], axis=1)

title_dummies_test = pd.get_dummies(test['Title_Simple'], prefix='Title')
test = pd.concat([test, title_dummies_test], axis=1)

# 모델 학습에 사용할 피처 목록 업데이트
inc_fts = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Gender', 
           'Embarked_C', 'Embarked_Q', 'Embarked_S',
           'Title_Master', 'Title_Miss', 'Title_Mr', 'Title_Mrs', 'Title_Rare']

# 모델 학습 및 예측
train_and_predict(train, test)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[7], line 14[0m
[0;32m      9[0m inc_fts [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mPclass[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mAge[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mSibSp[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mParch[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mFare[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mGender[39m[38;5;124m'[39m, 
[0;32m     10[0m            [38;5;124m'[39m[38;5;124mEmbarked_C[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEmbarked_Q[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEmbarked_S[39m[38;5;124m'[39m,
[0;32m     11[0m            [38;5;124m'[39m[38;5;124mTitle_Master[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mTitle_Miss[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mTitle_Mr[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mTitle_Mrs[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mTitle_Rare[39m[38;5;124m'[39m]
[0;32m     13[0m [38;5;66;03m# 모델 학습 및 예측[39;00m
[1;32m---> 14[0m train_and_predict(train, test)

[1;31mNameError[0m: name 'train_and_predict' is not defined

